[package]
name = "concrete_lib"
version = "0.1.2"
edition = "2018"
build = "build.rs"
authors = ["D. Ligier","S. Tap", "Zama team"]
license = "AGPL-3.0"
description = "Concrete is a fully homomorphic encryption (FHE) library that implements Zama's variant of TFHE."
homepage = "https://crates.io/crates/concrete_lib"
documentation = "https://zama.ai"
repository = "https://github.com/zama-ai/concrete"
readme = "README.md"

[build-dependencies]
cmake = { version = "0.1", optional = true}

[dev-dependencies]
criterion = "0.3"

[dependencies.fftw]
version = "^0.5.0"
default-features = false
features = ["system"]

[dependencies]
rand = "0.7"
rand_distr = "0.2.2"
num-traits = "0.2.12"
itertools = "0.9.0"
kolmogorov_smirnov = "1.1.0"
libc = "0.2.74"
num-integer = "0.1.43"
openssl = "0.10.30"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
backtrace = "0.3"
colored="2.0.0"

[lib]
name = "concrete_lib"
crate-type = ["cdylib", "rlib"]

[features]
gpu = ["cmake"]
cloud-computing = []
unsafe = []